service: backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-2
  httpApi:
    cors: true

functions:
  listDealers:
    handler: lambda/listDealers.handler
    events:
      - httpApi:
          method: GET
          path: /dealers
  listVehicles:
    handler: lambda/listVehicles.handler
    events:
      - httpApi:
          method: GET
          path: /vehicles/{bac}

plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-typescript
  - serverless-offline